language: node_js

node_js:
  - "9.2.1"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - 'npm install -g gatsby'

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  fqdn: 'jennle.com'
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
