language: node_js

node_js:
  - "6.9.4"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - 'npm install -g grunt-cli'

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  fqdn: 'jennle.com'
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
