language: node_js

node_js:
  - "7"

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - node_modules

before_script:
  - 'npm install -g grunt-cli'

script:
  - npm test
  - npm run build.prod

deploy:
  provider: pages
  skip_cleanup: true
  fqdn: 'jennle.com'
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
